# author: Paul Mooij
# date: 2019-06-14
# purpose: Build and Release template as Code for Database Project
# usage: copy this template; change variables & trigger; create Azure DevOps Pipeline; select this .yml file; rename Pipeline properly.
# hosted agent capabilities: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent

# using standard name pattern
name: $(Build.DefinitionName)_$(Date:yyyyMMdd).$(Rev:r)

# local template variables
variables:
 ProjectPath: 'samples/databases/wide-world-importers/wwi-sample.sln'
 BuildConfiguration: 'release'

# filter trigger down to specific solution folder
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - samples/databases/wide-world-importers/*


stages:
- stage: Build
  jobs:
  - job: VSBuild
    displayName: Visual Studio Build
    pool:
      vmImage: 'vs2017-win2016'

    steps:
    - task: VSBuild@1
      displayName: 'Build SQL projects'
      inputs:
        solution: 'samples/databases/wide-world-importers/**.sqlproj'
        platform: 'any cpu'
        configuration: '$(BuildConfiguration)'

    - task: SSISBuild@0
      displayName: 'Build SSIS project'
      inputs:
        projectPath: 'samples/databases/wide-world-importers/wwi-ssis/wwi-ssis'

#    - task: VSBuild@1
#      displayName: 'Build SSAS projects'
#      inputs:
#        solution: 'samples/databases/wide-world-importers/**.dwproj'
#        platform: 'any cpu'
#        configuration: '$(BuildConfiguration)'

    - task: VSBuild@1
      displayName: 'Build .NET projects'
      inputs:
        solution: 'samples/databases/wide-world-importers/wwi-*/**.csproj'
        platform: 'any cpu'
        configuration: '$(BuildConfiguration)'
        maximumCpuCount: true
        restoreNugetPackages: true

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**\bin\**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        flattenFolders: false

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.DefinitionName).zip'
        replaceExistingArchive: true
        verbose: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.DefinitionName).zip'


- stage: DeployDev
  dependsOn: Build
  jobs:
  - deployment: VSDeploy
    displayName: Visual Studio Deploy
    environment: Dev
    pool:
      name: Hosted Windows 2019 with VS2019
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              artifactName: 'drop'
              downloadType: 'single'
              downloadPath: '$(System.ArtifactsDirectory)'